# Sharpmake GitHub Actions CI configuration

name: build
on: [push, pull_request]
jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Install .NET Core 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - uses: actions/checkout@v2
      - name: Bootstrap
        shell: bash
        run: ./bootstrap.sh
      - name: Build
        shell: bash
        run: ./CompileSharpmake.sh Sharpmake.sln "${{ matrix.configuration }}"

  win:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v2
      - name: Bootstrap
        shell: cmd
        run: bootstrap.bat
      - name: Build
        shell: cmd
        run: CompileSharpmake.bat Sharpmake.sln "${{ matrix.configuration }}" "Any CPU"
      - name: UnitTest
        run: dotnet test tmp/bin/${{ matrix.configuration }}/Sharpmake.UnitTests/Sharpmake.UnitTests.dll
      - name: RegressionTest
        run: python regression_test.py

