# Sharpmake GitHub Actions CI configuration

name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true

    steps:
      - name: Install .NET Core 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - uses: actions/checkout@v2

      - name: Bootstrap.bat
        if: runner.os == 'Windows'
        shell: cmd
        run: bootstrap.bat

      - name: Bootstrap.sh
        if: runner.os != 'Windows'
        shell: bash
        run: ./bootstrap.sh

      - name: CompileSharpmake.bat
        if: runner.os == 'Windows'
        shell: cmd
        run: CompileSharpmake.bat Sharpmake.sln "${{ matrix.configuration }}" "Any CPU"

      - name: CompileSharpmake.sh
        if: runner.os != 'Windows'
        shell: bash
        run: ./CompileSharpmake.sh Sharpmake.sln "${{ matrix.configuration }}"

      - name: UnitTest
        if: runner.os == 'Windows'
        run: dotnet test tmp/bin/${{ matrix.configuration }}/Sharpmake.UnitTests/Sharpmake.UnitTests.dll

      - name: RegressionTest
        if: runner.os == 'Windows'
        run: python regression_test.py
