# Sharpmake GitHub Actions CI configuration

name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        configuration: [debug, release]

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true

    steps:
      - name: Install .NET Core 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Bootstrap.bat ${{ matrix.configuration }}
        if: runner.os == 'Windows'
        shell: cmd
        run: bootstrap.bat Sharpmake.Main.sharpmake.cs ${{ matrix.configuration }}

      - name: Bootstrap.dotnet.sh ${{ matrix.configuration }}
        if: runner.os != 'Windows'
        shell: bash
        run: ./bootstrap.dotnet.sh Sharpmake.Main.sharpmake.cs ${{ matrix.configuration }}

      - name: CompileSharpmake.bat ${{ matrix.configuration }}
        if: runner.os == 'Windows'
        shell: cmd
        run: CompileSharpmake.bat Sharpmake.sln "${{ matrix.configuration }}" "Any CPU"

      - name: CompileSharpmake.dotnet.sh ${{ matrix.configuration }}
        if: runner.os != 'Windows'
        shell: bash
        run: ./CompileSharpmake.dotnet.sh Sharpmake.sln "${{ matrix.configuration }}"

      - name: GenerateMdbFiles.bat
        if: runner.os == 'Windows' && matrix.configuration == 'release'
        shell: cmd
        run: GenerateMdbFiles.bat

      - name: UnitTest
        run: dotnet test tmp/unittests/${{ matrix.configuration }}/Sharpmake.UnitTests.dll

      - name: RegressionTest
        if: runner.os == 'Windows'
        run: python regression_test.py

      - name: FunctionalTest
        if: runner.os == 'Windows'
        run: python functional_test.py

      - name: Upload sharpmake cross-platform release binaries
        if: runner.os == 'Windows' && matrix.configuration == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: 'Sharpmake-${{github.sha}}'
          path: tmp/bin
