# Sharpmake GitHub Actions CI configuration

name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        configuration: [Debug, Release]

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true

    steps:
      - name: Install .NET Core 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Clean package cache as a temporary workaround for actions/setup-dotnet#155
        run: dotnet nuget locals all --clear 

      - name: Bootstrap.bat ${{ matrix.configuration }}
        if: runner.os == 'Windows'
        shell: cmd
        run: bootstrap.bat Sharpmake.Main.sharpmake.cs ${{ matrix.configuration }}

      - name: Bootstrap.dotnet.sh
        if: runner.os != 'Windows'
        shell: bash
        run: ./bootstrap.dotnet.sh

      - name: CompileSharpmake.bat
        if: runner.os == 'Windows'
        shell: cmd
        run: CompileSharpmake.bat Sharpmake.sln "${{ matrix.configuration }}" "Any CPU"

      - name: CompileSharpmake.dotnet.sh
        if: runner.os != 'Windows'
        shell: bash
        run: ./CompileSharpmake.dotnet.sh Sharpmake.sln "${{ matrix.configuration }}"

      - name: UnitTest
        if: runner.os == 'Windows'
        run: dotnet test tmp/unittests/${{ matrix.configuration }}/Sharpmake.UnitTests.dll

      - name: RegressionTest
        if: runner.os == 'Windows'
        run: python regression_test.py
